### PR TITLE
Fixes for standard and enterprise deployment issues

### PR DESCRIPTION
**Pull request by jeffpaineMS**
Resolves and Issue where terraform would crash with latest version, pins to 1.5.7
Resolves issue with GitHub ASA deploy task causing deployment to fail due to not having access to log stream, now uses az sping app deploy CLI
Standard GitHub action workflow will now allow destroy steps to run if app deployments fail

### CODE REVIEW

**Comment by luisfeliz79** [comment]
There may be an issue with the Standard-Petclinic sample deployment where , the az spring deploy step for api-gateway fails.  However, none of the files modified in this PR would have affected by this, meaning that the issue may have been there from before. I think we should move forward with this particular PR and create a separate issue for the problem I mentioned.

**Comment by luisfeliz79** [comment]
The issues with "the az spring deploy step for api-gateway fails" have been resolved!

**Review by luisfeliz79 — APPROVED** [review]
Reviewed and tested

**Comment by kriation** [comment]
@luisfeliz79, ready to merge?

**Pull request merged**
